# لیست ارزهای موردنظر

COINS = {
    "bitcoin": "BTC",
    "ethereum": "ETH",
    "tether": "USDT",
    "binancecoin": "BNB",
    "solana": "SOL",
    "ripple": "XRP",
    "cardano": "ADA",
    "dogecoin": "DOGE",
    "tron": "TRX",
    "avalanche-2": "AVAX",
    "polkadot": "DOT",
    "chainlink": "LINK",
    "litecoin": "LTC",
    "bitcoin-cash": "BCH",
    "stellar": "XLM",
    "filecoin": "FIL",
    "internet-computer": "ICP",
    "hedera-hashgraph": "HBAR",
    "aptos": "APT",
    "arbitrum": "ARB",
    "optimism": "OP",
    "near": "NEAR",
    "vechain": "VET",
    "algorand": "ALGO",
    "maker": "MKR",
    "aave": "AAVE",
    "the-sandbox": "SAND",
    "decentraland": "MANA",
    "shiba-inu": "SHIB",
    "pepe": "PEPE",
    "injective-protocol": "INJ",
    "render-token": "RNDR",
    "the-graph": "GRT",
    "theta-token": "THETA",
    "elrond-erd-2": "EGLD",
    "tezos": "XTZ",
    "flow": "FLOW"
}